### ISSUE TITLE
produce equivalent to yum.log (log of package installs, updates, and removes)

### ISSUE THREAD

**Issue by plaffiazho** [rpm-software-management/dnf-plugins-extras#100]
yum produced a nice neat log file which simply listed the dates and times for each package added, updated, and removed. This is extremely helpful for many purposes, such as:
1. tracking down which update caused a problem (useful in case it's necessary to revert to the older version, as well as for quality of bug reports to upstream)
2. tracking down how packages added/removed correlate with e.g. system performance or other issues
3. undoing a transaction (e.g. knowing all packages and dependencies which were installed if it's decided you don't want the software after all, or vis versa (think remove-with-leaves))
4. after-the-fact documentation of what software was manually added to an installation, which may need to be reproduced when migrating to another machine

An example of each type of entry in yum.log:
```
Apr 06 03:19:09 Updated: yum-3.2.29-81.el6.centos.noarch
May 25 20:10:54 Erased: postfix
Jul 12 05:59:27 Installed: kernel-2.6.32-696.3.2.el6.x86_64
```

Could this please be added to dnf?

Also, sorry if I've filed this in the wrong place -- it seems most of the dnf components don't allow reporting bugs / enhancement requests?

**Comment by Conan-Kudo** [comment]
@plaffiazho Bugs for DNF itself can be filed here: https://bugzilla.redhat.com/enter_bug.cgi?product=DNF

**Comment by j-mracek** [comment]
I believe that there is a bugzilla opened already.
