### ISSUE TITLE
--debug-solver does not work with system-upgrade download

### ISSUE THREAD

**Issue by cmurf** [rpm-software-management/dnf-plugins-extras#112]
When dnf system-upgrade download runs into conflicts, adding --debug-solver products an empty debugdata directory, so it's much harder to troubleshoot what the source of the problem is in the conflicting packages.

**Comment by j-mracek** [comment]
It looks like that the issue was resolved because I am unable to reproduce the issue on Fedora 29 with latest dnf-4.2.5
