### ISSUE TITLE
feature: system-upgrade should remove old rescue kernel and initramfs

### ISSUE THREAD

**Issue by cmurf** [rpm-software-management/dnf-plugins-extras#119]
Problem: Fedora creates a rescue kernel and initramfs pair at initial installation, which are never updated.

This pair is created by /etc/kernel/postinst.d/51-dracut-rescue-postinst.sh found in dracut-config-rescue-046-5.fc27.x86_64 which is part of the dracut package, and only happens if the rescue items are missing, which most typically is only at initial installation.

Solution: Delete the two rescue files before new major version kernel RPMs are installed. This will ensure replacement rescue kernel and initramfs are automatically generated.

**Comment by j-mracek** [comment]
I am sorry, but I believe that this should be handled by kernel-core scriptlets. Please could you open a bugzilla on the kernel-core and start a discussion there?
