### ISSUE TITLE
System-upgrade to rawhide tries to fetch nonexistent repo

### ISSUE THREAD

**Issue by Edicatax** [rpm-software-management/dnf-plugins-extras#147]
An upgrade from F29 to rawhide fails because it tries to pull a repo that doesn't exist:
[upgrade.txt](https://github.com/rpm-software-management/dnf-plugins-extras/files/2861534/upgrade.txt)
Pulling the metalink manually reveals that while the upgrade looks for `fedora-modular-rawhide` it likely should be looking for `rawhide-modular` instead.

**Comment by j-mracek** [comment]
I am sorry, but this not a proper place for the report. Please could you try a bugzilla https://bugzilla.redhat.com/ and report the issue on distribution. I believe that there is no issue in dnf. It only processes information provided from dnf.conf, *.repo files and from user from commandline.

**Comment by ydroneaud** [comment]
Issue is reported as https://bugzilla.redhat.com/show_bug.cgi?id=1686459
