### ISSUE TITLE
tracer: RPM packages for Fedora 21

### ISSUE THREAD

**Issue by FrostyX** [rpm-software-management/dnf-plugins-extras#19]
Hello,
I want to ask you, if it would be possible to continue building rpm packages for Fedora 21.

One thing is that latest version of package `dnf-plugins-extras-tracer` in the repository is basically broken. It throws traceback every time. In the next commit, you fixed it by yourself, @ignatenkobrain and for F22 it works, but there are missing builds for F21.

Moreover, Tracer is my thesis and I will probably hand it over to my opponent in a few weeks and it would be nice if he gets the latest version. Ofc I don't know what version of Fedora he will use, but F21 is current stable, so I guess that will be it.

Thank you,
FrostyX

**Comment by ignatenkobrain** [comment]
please, report to bugzilla.redhat.com ;)

**Comment by FrostyX** [comment]
See <https://bugzilla.redhat.com/show_bug.cgi?id=1213964>
