### ISSUE TITLE
Add virtual Provides for offline-upgrade and offline-distrosync commands

### ISSUE THREAD

**Issue by mattdm** [rpm-software-management/dnf-plugins-extras#194]
PR here https://src.fedoraproject.org/fork/mattdm/rpms/dnf-plugins-extras/c/d24b2e09de9afd1021a4e31f9e777d7de936caa5 already applied in Fedora dist-git but mentioning it here so it doesn't get lost. Simply needs

```

Provides:       dnf-command(offline-upgrade)
Provides:       dnf-command(offline-distrosync)

```

added to the `python3-dnf-plugin-system-upgrade` subpackage.

**Comment by kontura** [comment]
Like mentioned in the downstream [PR](https://src.fedoraproject.org/rpms/dnf-plugins-extras/pull-request/2) this is already resolved here: https://github.com/rpm-software-management/dnf-plugins-extras/pull/193 and https://github.com/rpm-software-management/dnf-plugins-extras/pull/192.

Thank you. :+1:
