### ISSUE TITLE
Test suite leaves /tmp/system_upgrade_test_installroot-* behind

### ISSUE THREAD

**Issue by scfc** [rpm-software-management/dnf-plugins-extras#206]
Each run of the test suite, for example as part of `fedpkg local`, leaves around two dozen mostly empty `/tmp/system_upgrade_test_installroot-*` directories behind.

This should probably be fixed by amending `/tmp/system_upgrade_test_installroot-*`'s `CommandTestCaseBase.tearDown()` to do `shutil.rmtree(self.installroot)` as well, **but** in earlier versions `self.cli.base.conf.installroot` was set to `/`, so an appropriate amount of caution should be applied.  (Maybe set `self.installroot` to the result of a `tempfile.TemporaryDirectory()` call, `self.cli.base.conf.installroot` to `self.installroot.name`, and call `self.installroot.cleanup()` in `CommandTestCaseBase.tearDown()`.)

**Comment by m-blaha** [comment]
Fixed by https://github.com/rpm-software-management/dnf-plugins-extras/pull/207
