### ISSUE TITLE
 [WSL] System has not been booted with systemd as init system (PID 1). Can't operate.

### ISSUE THREAD

**Issue by lukeyeager** [rpm-software-management/dnf-plugins-extras#211]
(was https://github.com/rpm-software-management/dnf-plugin-system-upgrade/issues/60)

I installed fedora 35 as a WSL distribution following this guide: https://dev.to/bowmanjd/install-fedora-on-windows-subsystem-for-linux-wsl-4b26

Then, I tried to follow these instructions to upgrade to 36: https://docs.fedoraproject.org/en-US/quick-docs/dnf-system-upgrade/

Here is the error I encountered:
```console
$ sudo dnf system-upgrade download --releasever=36
$ sudo dnf system-upgrade reboot
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```
I found the `system-upgrade upgrade` command, ran it, and that seemed to work. Is this expected behavior?

**Comment by kontura** [comment]
I don't really know what is expected from `systemd` on `WSL`, the main reason we do the reboot is to run the usually huge dnf upgrade transaction without graphical environment - which can crash and kill the transaction in the middle. Although I guess this is not a problem on `WSL`.

Maybe you could just use the `distro-sync` command which doesn't use `systemd`. Some instruction should be [here](https://docs.fedoraproject.org/en-US/quick-docs/upgrading-fedora-online/).

**Comment by lukeyeager** [comment]
Ok, no problem. I just thought I'd share so you were aware of a failure(?) mode. Also, I just discovered that there's now support for systemd in wsl if you're on a new enough windows+wsl: https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/.
