### ISSUE TITLE
post-transaction-actions not triggered

### ISSUE THREAD

**Issue by tdewolff** [rpm-software-management/dnf-plugins-extras#221]
I've added the following line to `/etc/dnf/dnf.conf`:

```
pluginconfpath=/etc/dnf/plugins
```

I've create the file `/etc/dnf/plugins/post-transaction-actions.conf`:

```
[main]
enabled = 1
actiondir = /etc/dnf/plugins/post-transaction-actions.d/
```

I've created `/etc/dnf/plugins/post-transaction-actions.d/test.action`:

```
*:any:echo "DOES IT WORK?" >> /tmp/trans.log
```

But the action is never executed. I'm running CentOS Stream 8 and `dnf-plugin-extras` is installed. What could be wrong here?

**Comment by dcantrell** [comment]
What OS does this happen on?  And what version of dnf?

**Comment by tdewolff** [comment]
Most likely I must have missed a configuration for this to work? Examples are scarce. 

```
# dnf --version
4.7.0
  Installed: dnf-0:4.7.0-20.el8.noarch at Wed 17 Jan 2024 02:24:17 AM GMT
  Built    : builder@centos.org at Mon 16 Oct 2023 01:48:29 PM GMT

  Installed: rpm-0:4.14.3-31.el8.x86_64 at Wed 17 Jan 2024 02:23:59 AM GMT
  Built    : builder@centos.org at Wed 13 Dec 2023 02:00:08 PM GMT
```

**Comment by dcantrell** [comment]
On CentOS Stream 8, this will work if you install the python3-dnf-plugin-post-transaction-actions.  I just confirmed it locally.

**Comment by tdewolff** [comment]
Thanks, that was it!
