### ISSUE TITLE
python-dnf-plugins-extras-local does not create /var/lib/dnf/plugins/local directory

### ISSUE THREAD

**Issue by Claes1981** [rpm-software-management/dnf-plugins-extras#32]
Hi,

The local plugin does not create it's repository directory on my Fedora 22 computer. 
Dnf-commands output the message "local: '/var/lib/dnf/plugins/local' is not a directory".

Claes

**Comment by ignatenkobrain** [comment]
Report to bugzilla.redhat.com please. It's already there, so don't report this. I will fix it.

**Comment by Claes1981** [comment]
ok, did not know that.

**Comment by rholy** [comment]
@ignatenkobrain, you may want to disable this issue tracker: https://help.github.com/articles/disabling-issues/

**Comment by ignatenkobrain** [comment]
@rholy I can't. I'm not admin in @rpm-software-management/owners

**Comment by rholy** [comment]
Ah, so, do you want @jsilhan to disable it?

**Comment by ignatenkobrain** [comment]
@rholy I want to disable it. I think you can also do this.
