### ISSUE TITLE
post-transaction actions

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/dnf-plugins-extras#63]
https://bugzilla.redhat.com/show_bug.cgi?id=1220182

```
We're just looking for the ability to configure arbitrary commands to run after certain packages are acted on.

For yum this was implemented in yum-plugin-post-transaction-actions ... if this were re-implemented for dnf, I think everyone would be happy, but I doubt anyone needs it to be implemented in exactly the same way (particularly because it doesn't seem to be very well documented), so long as it can accomplish the same thing.

Here's the description of yum-plugin-post-transaction-actions:
Yum plugin to run arbitrary commands when certain pkgs are acted on
This plugin allows the user to run arbitrary actions immediately following a transaction when specified packages are changed.

My understanding is that it creates a directory at /etc/yum/post-actions ... in that directory, a user could place "action" files for each package the user wishes to have post transaction actions apply to (e.g., the user could create a file named kernel.action if they want to run a command after the kernel is updated (actually, I don't think it matters what the file name is, as long as it ends in ".action", since the package name must be specified inside the file)) ... inside the file the user would enter the package name, an action (e.g. install or update), and the path to a script to run, like follows ...
kernel:update:/path-to/script-to-run.sh

In this case, the script will run any time the kernel package is updated.

You can also pass variables such as the package version to the script, like follows ...
kernel:update:/path-to/script-to-run.sh $ver $rel $arch
```

**Comment by svenbroeker** [comment]
it would be nice to make it univeral for other hooks like pre-transaction,pre-download,post-download etc.

**Comment by Shulyaka** [comment]
This issue keeps me still using yum on one of my machines for unattended updates. The use case for thix plugin is actually quite big:
* Fix permissions after ngnix update
* Run 'occ upgrade' on owncloud update
* Install printer drivers on hplip update
* Restart certain services on update or schedule a system restart on a kernel update
* etc

**Comment by girst** [comment]
Is this still being worked on or has it been shelved? I am also needing this functionality for similar reasons to Shulyaka's.

**Comment by freddyw** [comment]
I am also still hoping this will be implemented (some day).

**Comment by aairey** [comment]
Still looking to have this implemented @m-blaha ? Or anyone else that could comment?
Seems it is a bit stale since 2.5 years, but it would still a great plugin so we are able to run some hooks after a kernel update.

**Comment by j-mracek** [comment]
I believe that issue could be solved using rpm scriptlets. Please is there any reason why scriptlets cannot solve the request?

**Comment by plagrotrou** [comment]
@j-mracek 

i believe rpm scriptlets are only a solution for authors of the rpm files, whereas post-transaction actions allows end users to configure commands to run after packages are updated. for example, maybe a user wants to automatically reboot after a kernel update. that's just one odd example.

**Comment by aairey** [comment]
Here is the source of the previous YUM plugin mentioned by OP:

https://github.com/rpm-software-management/yum-utils/blob/master/plugins/post-transaction-actions/post-transaction-actions.py

**Comment by mathieu-aubin** [comment]
Would love to have this functionnality as well

**Comment by wi24rd** [comment]
I found this:
https://github.com/rpm-software-management/dnf-plugins-core/blob/master/plugins/post-transaction-actions.py
seems done?
I haven't tried and don't know whether it works now because I idle my fedora for a long time.

**Comment by t-gergely** [comment]
> I haven't tried and don't know whether it works now because I idle my fedora for a long time.

It works for me from package _python3-dnf-plugin-post-transaction-actions._ (Unfortunately, action command must be single line.)
