### ISSUE TITLE
Package does not meet expectations

### ISSUE THREAD

**Issue by xenithorb** [rpm-software-management/dnf-plugins-extras#96]
The way that this is currently packaged in fedora, there are only man pages included in the package

```
$ rpm -ql dnf-plugins-extras
/usr/share/man/man8/dnf.plugin.debug.8.gz
/usr/share/man/man8/dnf.plugin.kickstart.8.gz
/usr/share/man/man8/dnf.plugin.leaves.8.gz
/usr/share/man/man8/dnf.plugin.local.8.gz
/usr/share/man/man8/dnf.plugin.migrate.8.gz
/usr/share/man/man8/dnf.plugin.repoclosure.8.gz
/usr/share/man/man8/dnf.plugin.repograph.8.gz
/usr/share/man/man8/dnf.plugin.repomanage.8.gz
/usr/share/man/man8/dnf.plugin.rpmconf.8.gz
/usr/share/man/man8/dnf.plugin.show-leaves.8.gz
/usr/share/man/man8/dnf.plugin.snapper.8.gz
/usr/share/man/man8/dnf.plugin.tracer.8.gz
/usr/share/man/man8/dnf.plugin.versionlock.8.gz
```

Nor does it have any dependencies on the actual packages....

I suspect that all of these have been broken into their own packages as that what seems to be revealed by my quick package search for `dnf plugins` - but that can be quite confusing too because there are both `python` and `python3` versions for each. From a user perspective it's getting increasingly confusing...

Why not either remove the `dnf-plugins-extras` package, or better yet, make it into a meta package that installs the valid set of plugins as dependencies? (the set that it currently has mans for) 

This way a user could install `dnf-plugins-extras` again and have all of them at once.  

Otherwise, I fail to see why the package is even left behind to confuse people.

Edit: additionally, the package description in the spec is a "lie": 

```
Available Packages
Name        : dnf-plugins-extras
Arch        : noarch
Epoch       : 0
Version     : 0.0.12
Release     : 4.fc25
Size        : 29 k
Repo        : fedora
Summary     : Extras Plugins for DNF
URL         : https://github.com/rpm-software-management/dnf-plugins-extras
License     : GPLv2+
Description : Extras Plugins for DNF.
```

**Comment by ignatenkobrain** [comment]
0.0.12 is not latest release, latest release exists in F26+ and packaging is different there.
